### ISSUE TITLE
Parsing

### ISSUE THREAD

**Issue by raphaelyancey** [raphaelyancey/cli2compose#1]
```
docker run --name elasticsearch -e "http.host=0.0.0.0" -e "ES_JAVA_OPTS=-Xms512m -Xmx512m" -d docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
```

results in

```
version: "2"
services:
  app:
    image: -X
    command: -m -x -5 -1 -2 -m -"
      docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    container_name: elasticsearch
    environment:
      - '"http.host=0.0.0.0"'
      - '"ES_JAVA_OPTS=-Xms512m'
```
